### ISSUE TITLE
서빙) Streamlit Wireframe 작성

### ISSUE THREAD

**Issue by nonegom** [boostcampaitech3/final-project-level3-nlp-09#50]
Task 수행이유: 초기 계획한 데모 형식과 달리 챗봇 형식으로 진행한 부분 추가

**Comment by HanNayeoniee** [comment]
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/33839093/173170812-14c74642-2e3a-4b78-b61b-7bd133bd8862.png">

> 변경 전 와이어 프레임


<img width="1069" alt="image" src="https://user-images.githubusercontent.com/33839093/173170801-7512aae9-0898-4568-89f5-ce520c3c075d.png">

> 변경 후 와이어 프레임
> - 초기 와이어 프레임에서 사이드바를 추가하여 직관적인 구조로 변경
> - 사용자에게 구어체로 질문을 입력 받기 위한 **챗봇** 레이아웃 도입
