### ISSUE TITLE
서빙) 엘라스틱 서치 회의록 추가/삭제 기능과 연결

### ISSUE THREAD

**Issue by nonegom** [boostcampaitech3/final-project-level3-nlp-09#62]
- 회의록 삭제:`delete_doc()` 사용해 사용자 인덱스별 들어있는 문서(회의록) 삭제
- 회의록 추가: `insert_data_st()`를 사용해 회의록 파일명을 id값으로 가지는 회의록 본문을 삽입

**Comment by HanNayeoniee** [comment]
회의록 업로드/삭제 기능이 한 템포씩 늦어지는 문제 해결
