### ISSUE TITLE
서빙) 문서 하이라이트 표시

### ISSUE THREAD

**Issue by nonegom** [boostcampaitech3/final-project-level3-nlp-09#70]
Task수행이유: 찾아온 답이 회의록 어디에 있었는지 보여줌으로써 사용자에게 서비스에 대한 신뢰성을 높여주기 위함

**Comment by detailTales** [comment]
html의 스타일을 이용하여 정답 위치에 배경 색을 넣어 하이라이팅
![image](https://user-images.githubusercontent.com/95160107/172589398-d611368e-1bd4-4ea9-a1e6-6accea071271.png)


정답을 찾지 못한 경우 찾지 못함을 알림
![image](https://user-images.githubusercontent.com/95160107/172589229-6d566d14-8242-4adb-8385-f5a67a92c0e0.png)
