### ISSUE TITLE
마무리) README 작성

### ISSUE THREAD

**Issue by nonegom** [boostcampaitech3/final-project-level3-nlp-09#77]
Task수행이유: 프로젝트 마무리 후, 프로젝트의 전반적인 내용을 소개하기 위해 발표 ppt의 흐름에 따라 README.md 작성

**Comment by wogkr810** [comment]
GIthub Main의 [README.md](https://github.com/boostcampaitech3/final-project-level3-nlp-09/blob/main/README.md)에 작성 완료
