### ISSUE TITLE
안녕하세요,,

### ISSUE THREAD

**Issue by sehee-jeong** [boostcampaitech3/final-project-level3-nlp-09#85]
안녕하세요.
제가 제 레포인 줄 알고 착각하고 엇 데이터가 이상하네 하고 파일명이랑 파일을 변경 하려던 걸 여러분 레포에 변경 시도(pull requests)를 하였습니다,,
그냥 무시해주시면 정말 감사드리겠습니다ㅠㅠ,,,
죄송합니다...ㅠ

**Comment by HanNayeoniee** [comment]
괜찮습니다 :)
fork하신 후에 마음껏 사용하세요!
